name: Laws

on:
  workflow_dispatch: # manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISH_TO_PAGES: ${{ secrets.PUBLISH_TO_PAGES }}

    steps:
    - uses: actions/checkout@v6
    - name: Restore cache
      uses: coursier/cache-action@v8
    - name: Set up JDK 21 & Scala
      uses: coursier/setup-action@v3
      with:
        jvm: 21
        apps: sbt
    - name: Run Laws
      run: sbt "laws/test"
