name: Laws

on:
  workflow_dispatch: # manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Restore cache
      uses: coursier/cache-action@v6
    - name: Set up JDK 17 & Scala
      uses: coursier/setup-action@v1
      with:
        jvm: 17
        apps: sbt
    - name: Run Laws
      run: sbt laws/test
